name: Audio Doctor
favicon: null
layout_spectrum: 0.80085
typography_spectrum: 0.84206
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#5b5b5d'
    - '#05040c'
    - '#afafaf'
    - '#a69c03'
  brandStrength: 0.5625
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.75
purpose: []
