name: Audio Doctor
favicon: null
layout_spectrum: 0.6238
typography_spectrum: 0.9637193439994007
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#002f67'
    - '#29000b'
    - '#e71900'
    - '#ffa929'
    - '#576f00'
  brandStrength: 0.75
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.75
purpose: []
