name: Audio Doctor
favicon: null
layout_spectrum: 0.6238
typography_spectrum: 0.9637193439994007
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fefff7'
    - '#ffda89'
    - '#dfa75c'
    - '#110a00'
    - '#a9520d'
  brandStrength: 0.875
  lightness: 0.1365035583730787
  saturation: 0.6875
  rhythmicContrast: 0.4522668363060802
purpose: []
